plant:
  module: "Plants.CournotPlant"
  class: "CournotPlant"
  params:
    p_max: 2.0
    c_m: 0.1

controller:
  module: "Controller.ClassicalController"
  class: "ClassicalController"
  params:
    params: [0.0, 0.0, 0.0]

simulation:
  initial_state: [0.0, 0.5]
  setpoint: 0.3
  time_steps: 20
  disturbance_range: [-0.000001, 0.0000001]
  seed: 1337

training:
  epochs: 20
  learning_rate: 0.01
